# SPDX-License-Identifier: MIT-0
---
# vars for all hosts in staging env

timezone: America/New_York
ansible_python_interpreter: /usr/bin/python3
secret_files:
  - src: ~/.github_pat
    dest: '/home/{{ ansible_user }}/.github_pat'
    owner: '{{ ansible_user }}'
    mode: '0600'
