# SPDX-License-Identifier: MIT-0
---
# tasks file for set_secrets

- name: Copy secret files to target host
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: '{{ item.owner }}'
    mode: '{{ item.mode }}'
  loop: '{{ secrets }}'
  when: secret_files | length > 0
  no_log: true
  notify: Restart ansible-keychain
