# SPDX-License-Identifier: MIT-0
---
# tasks file for server_config

- name: Gather all regular users
  ansible.builtin.getent:
    database: passwd
  register: passwd_entries

- name: Filter regular users
  set_fact:
    regular_users: "{{ passwd_entries.passwd | selectattr('uid', '>=', 1000) | selectattr('name', 'ne', 'nobody') | list }}"

- name: Copy dotfiles for each user
  ansible.builtin.copy:
    src: '{{ dotfiles_src_dir }}/{{ item.src }}'
    dest: '/home/{{ user.name }}/{{ item.dest }}'
    owner: '{{ user.name }}'
    group: '{{ user.name }}'
    mode: '0644'
    backup: yes
  loop: '{{ dotfiles }}'
  loop_control:
    loop_var: item
  with_items: '{{ regular_users }}'
