# SPDX-License-Identifier: MIT-0
---
# tasks file for ssh_access

- name: Compile and set authorized_keys for users
  ansible.builtin.template:
    src: authorized_keys.j2
    dest: '/home/{{ item.name }}/.ssh/authorized_keys'
    owner: '{{ item.name }}'
    group: '{{ item.name }}'
    mode: '0600'
  loop: '{{ ssh_users }}'
  loop_control:
    loop_var: item
