# SPDX-License-Identifier: MIT-0
---
# tasks file for cloning ansible repo - bootstrap

- name: Mark /opt/ansible as a safe git directory
  community.general.git_config:
    name: safe.directory
    value: /opt/ansible
    scope: global
  become: true
  when: inventory_hostname in groups['ansible_control']

- name: Clone Ansible repository
  ansible.builtin.git:
    repo: 'https://github.com/kylar514/ans-homelab.git'
    dest: /opt/ansible
    version: master
    update: yes
    force: yes
  become: true
  become_user: root
  when: inventory_hostname in groups['ansible_control']

- name: Fix ownership of cloned repo
  ansible.builtin.file:
    path: /opt/ansible
    owner: ansible
    group: ansible
    recurse: yes
  become: true
  when: inventory_hostname in groups['ansible_control']
