# SPDX-License-Identifier: MIT-0
---
# tasks file for cloneing ansible repo - bootstrap

- name: Ensure repo directory exists
  ansible.builtin.file:
    path: /opt/ansible
    state: directory
    owner: ansible
    group: ansible
    mode: '0755'

- name: Clone Ansible repository
  ansible.builtin.git:
    repo: 'https://github.com/kylar514/ans-homelab.git'
    dest: /opt/ansible
    version: master
    update: yes
    force: yes
  become: true
  become_method: sudo
  when: inventory_hostname in groups['ansible_control']
