#SPDX-License-Identifier: MIT-0
---
# tasks file for unattended_upgrades
- name: Configure unattended-upgrades
  copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Download-Upgradable-Packages "1";
      APT::Periodic::AutocleanInterval "7";
      APT::Periodic::Unattended-Upgrade "1";
    owner: root
    group: root
    mode: '0644'

- name: Ensure unattended-upgrades service is enabled and running
  systemd:
    name: unattended-upgrades
    enabled: yes
    state: started
