# SPDX-License-Identifier: MIT-0
---
# UFW rules for this host/group.
# Each entry supports:
#   port:   The port number to allow/deny
#   proto:  Protocol ('tcp' or 'udp'), defaults to 'tcp'
#   rule:   'allow' or 'deny', defaults to 'allow'

ufw_default_routed: 'allow'

group_ufw_rules:
  # Allow API Server
  - port: 6443
    proto: tcp
    rule: allow
  # Allow HTTPS
  - port: 443
    proto: tcp
    rule: allow
  - port: 8472
    proto: udp
    rule: allow
  - src: '10.42.0.0/16' #k3s pod cidr
    rule: allow
    proto: any
  - src: '10.43.0.0/16' #k3s service cidr
    rule: allow
    proto: any
