# SPDX-License-Identifier: MIT-0
---
# group_vars for ansible_control

secret_files:
  - src: ~/.ssh/ansible
    dest: '/home/{{ansible_user}}/.ssh/ansible'
    owner: '{{ ansible_user }}'
    mode: '0600'
  - src: ~/.ansible_vault_pass
    dest: '/home/{{ ansible_user }}/.ansible_vault_pass'
    owner: '{{ ansible_user }}'
    mode: '0600'
  - src: ~/.github_runner_pat
    dest: '/home/{{ansible_user}}/.github_runner_pat'
    owner: '{{ ansible_user }}'
    mode: '0600'
