#SPDX-License-Identifier: MIT-0
---
# tasks file for install_keepalived
- name: Install keepalived
  package:
    name: keepalived
    state: present
  when: "'vip_failover' in group_names"

- name: Configure keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart keepalived
  when: "'vip_failover' in group_names"

- name: Enable and start keepalived
  systemd:
    name: keepalived
    enabled: yes
    state: started
  when: "'vip_failover' in group_names"
