# SPDX-License-Identifier: MIT-0
---
# tasks file for ufw

- name: Set UFW default incoming policy to deny
  ufw:
    direction: incoming
    policy: deny

- name: Set UFW default outgoing policy to allow
  ufw:
    direction: outgoing
    policy: allow

- name: Enable ssh
  ufw:
    rule: 'allow'
    port: '22'
    proto: tcp

- name: Apply additional UFW rules from ufw_rules variable
  ufw:
    rule: "{{ item.rule | default('allow') }}"
    port: '{{ item.port }}'
    proto: "{{ item.proto | default('tcp') }}"
  loop: '{{ ufw_rules }}'
  when: item.groups | intersect(group_names) | length > 0

- name: Enable UFW
  ufw:
    state: enabled
