# SPDX-License-Identifier: MIT-0
---
# tasks file for actions_runner install (included)

- name: "Ensure install directory for {{ runner_repo.name }}"
  ansible.builtin.file:
    path: "{{ actions_runner_base_dir }}-{{ runner_repo.name }}"
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'

- name: "Extract runner archive for {{ runner_repo.name }}"
  ansible.builtin.unarchive:
    src: '/tmp/actions-runner.tar.gz'
    dest: "{{ actions_runner_base_dir }}-{{ runner_repo.name }}"
    remote_src: true
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
  when: existing_runners.matched == 0
