# SPDX-License-Identifier: MIT-0
---
# tasks file for actions_runner service start (included)

- name: "Enable and start runner service for {{ runner_repo.name }}"
  ansible.builtin.systemd:
    name: "actions-runner-{{ runner_repo.name }}.service"
    state: started
    enabled: true
    scope: user
    daemon_reload: true
  become_user: '{{ ansible_user }}'
