#SPDX-License-Identifier: MIT-0
---
# tasks file for sys_packages

- name: Ensure required packages are installed
  package:
    name: '{{ item }}'
    state: present
    update_cache: yes
  loop: '{{ base_packages }}'

- name: Packages for ansible control node
  package:
    name: '{{ item }}'
    state: present
    update_cache: yes
  loop: '{{ ansible_control_node }}'
  when: "'ansible_control' in group_names"
