# SPDX-License-Identifier: MIT-0
---
# handlers file for set_secrets
- name: Restart ansible-keychain
  ansible.builtin.systemd:
    name: ansible-keychain.service
    state: restarted
    scope: user
  become_user: '{{ ansible_user }}'
