# SPDX-License-Identifier: MIT-0
---
all_users:
  - name: ansible
    group: ansible
    shell: /bin/bash
    sudo: true
  - name: zeal
    group: zeal
    shell: /bin/bash
    sudo: true
    groups:
      - ansible
