# SPDX-License-Identifier: MIT-0
---
# defaults file for set_secrets
# see inventory defaults for ansible control node settings.

secret_files: []
# Each entry:
#   - src: /path/on/controller
#     dest: /path/on/target
#     owner: zeal
#     mode: '0600'
