# SPDX-License-Identifier: MIT-0
---
# Setup for Ansible, can be ran to bootstrap control node and update it.
# Run with: ansible_setup playbooks/ansible-setup.yml
- name: Base setup for Azir
  hosts: ansible_control
  become: true
  roles:
    - ssh_access
    - sys_packages
    - unattended_upgrades
    - set_keychain
    - set_ci
