# SPDX-License-Identifier: MIT-0
---
# Base system configuration applied to all managed hosts.

- name: Base system setup
  hosts: all
  roles:
    - timezone
    - users
    - ssh_access
    - sys_packages
    - copy_files
    - ufw
    - nfs_client
    - unattended_upgrades
