# SPDX-License-Identifier: MIT-0
---
# tasks file for server_config

- name: Copy files to server
  ansible.builtin.copy:
    src: '{{ inventory_dir }}/files/{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
    mode: "{{ item.mode | default('0644') }}"
  loop: '{{ ansible_key }}'
  loop_control:
    loop_var: item
