# SPDX-License-Identifier: MIT-0
---
name: Prod CI/CD

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Source SSH agent environment
        run: |
          source ~/.keychain/azir-sh
          ansible-playbook playbooks/site.yml \
            --vault-password-file ~/.ansible_vault_pass
