# SPDX-License-Identifier: MIT-0
---
name: Prod CI/CD

on:
  push:
    branches: [master]

jobs:
  site:
    name: Run site.yml

    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      # - name: Check for infrastructure changes
      #   id: changed
      #   uses: tj-actions/changed-files@v44
      #   with:
      #     files: |
      #       playbooks/**
      #       roles/**
      #       inventories/**

      - name: Install Ansible collections
        run: |
          cd ${{ github.workspace }}
          ansible-galaxy collection install -r requirements.yml

      - name: Run site.yml against prod
        # if: steps.changed.outputs.any_changed == 'true'
        env:
          VAULT_ADDR: ${{ vars.VAULT_ADDR }}
          VAULT_ROLE_ID: ${{ vars.VAULT_ROLE_ID }}
          VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}

        run: |
          cd ${{ github.workspace }}
          ansible-playbook playbooks/site.yml
